apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: isaacwang4076-leetcodesolver
spec:
  selector:
    matchLabels:
      app: isaacwang4076-leetcodesolver
      tier: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: isaacwang4076-leetcodesolver
        tier: backend
    spec:
      containers:
        - name: isaacwang4076-leetcodesolver
          image: simonfong6/isaacwang4076-leetcodesolver:0.11
          ports:
            - containerPort: 9292
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
